[package]
name = "kudos"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.6.4"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.14.0" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.26.0" }

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true

[tool.fmt]
sort-module-level-items = true

[scripts]
test = "snforge test"
